//PAGE INCREMENT ACTIONS
export const PAGE_INCREMENT = 'PAGE_INCREMENT';
export const PAGE_INCREMENT_NORMAL = 'PAGE_INCREMENT_NORMAL';

//PAGE DECREMENT ACTIONS
export const PAGE_DECREMENT = 'PAGE_DECREMENT';

//INITIAL FETCH ACTIONS
export const INITIAL_FETCH = 'INITIAL_FETCH';
export const INITIAL_FETCH_START = 'INITIAL_FETCH_START';
export const INITIAL_FETCH_SUCCESS = 'INITIAL_FETCH_SUCCESS';
export const INITIAL_FETCH_FAIL = 'INITIAL_FETCH_FAIL';