//Pager actions
export const PAGE_INCREMENT = 'PAGE_INCREMENT';
export const PAGE_DECREMENT = 'PAGE_DECREMENT';

export const INITIAL_FETCH = 'INITIAL_FETCH';
export const INITIAL_FETCH_SAGA_START = 'INITIAL_FETCH_SAGA_START';
export const INITIAL_FETCH_SAGA = 'INITIAL_FETCH_SAGA';